# OpenAI API 키를 아래 문자열 안에 입력해주세요
# 예시: OPENAI_API_KEY = "sk-abcdefghijklmnopqrstuvwxyz123456789"
# API 키는 https://platform.openai.com/api-keys 에서 발급받을 수 있습니다
# 주의: 실제 API 키를 이 파일에 직접 입력하지 마세요. 이 파일을 처음 복제한 후에만 로컬에서 수정하세요.
OPENAI_API_KEY = "" 